//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPO_USUARIO
    {
        public TBL_TIPO_USUARIO()
        {
            this.TBL_USUARIOS_LOG = new HashSet<TBL_USUARIOS_LOG>();
        }
    
        public int C_CONSECUTIVO { get; set; }
        public string C_NOM_TIPO { get; set; }
    
        public virtual ICollection<TBL_USUARIOS_LOG> TBL_USUARIOS_LOG { get; set; }
    }
}
