
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_V.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_BITACORA_ERRORES
{

    public int C_CONSECUTIVO { get; set; }

    public string C_PROCEDIMIENTO { get; set; }

    public int C_LINEA { get; set; }

    public string C_MENSAJE { get; set; }

    public System.DateTime C_FECHA_HORA { get; set; }

}

}
