
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_V.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_JUGADORES
{

    public TBL_JUGADORES()
    {

        this.TBL_CORREOS = new HashSet<TBL_CORREOS>();

        this.TBL_GOLEADORES = new HashSet<TBL_GOLEADORES>();

        this.TBL_TELEFONOS = new HashSet<TBL_TELEFONOS>();

        this.TBL_JUG_X_EQUIPO = new HashSet<TBL_JUG_X_EQUIPO>();

    }


    public int C_CONSECUTIVO { get; set; }

    public int C_FK_PROVINCIA { get; set; }

    public int C_FK_CANTON { get; set; }

    public int C_FK_DISTRITO { get; set; }

    public string C_CEDULA { get; set; }

    public string C_GENERO { get; set; }

    public System.DateTime C_NACIMIENTO { get; set; }

    public string C_NOMBRE { get; set; }

    public string C_APELLIDO1 { get; set; }

    public string C_APELLIDO2 { get; set; }

    public string C_DIRECCION { get; set; }

    public Nullable<bool> C_ACTIVO { get; set; }



    public virtual TBL_CANTON TBL_CANTON { get; set; }

    public virtual ICollection<TBL_CORREOS> TBL_CORREOS { get; set; }

    public virtual TBL_DISTRITO TBL_DISTRITO { get; set; }

    public virtual ICollection<TBL_GOLEADORES> TBL_GOLEADORES { get; set; }

    public virtual TBL_PROVINCIA TBL_PROVINCIA { get; set; }

    public virtual ICollection<TBL_TELEFONOS> TBL_TELEFONOS { get; set; }

    public virtual ICollection<TBL_JUG_X_EQUIPO> TBL_JUG_X_EQUIPO { get; set; }

}

}
