//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIOS_LOG
    {
        public TBL_USUARIOS_LOG()
        {
            this.TBL_INGRESOS_X_USUARIO = new HashSet<TBL_INGRESOS_X_USUARIO>();
            this.TBL_ENC_TORNEOS = new HashSet<TBL_ENC_TORNEOS>();
        }
    
        public int C_CONSECUTIVO { get; set; }
        public string C_NOMBRE { get; set; }
        public string C_APELLIDO1 { get; set; }
        public string C_APELLIDO2 { get; set; }
        public string C_NOM_USUARIO { get; set; }
        public string C_PASS { get; set; }
        public Nullable<bool> C_ACTIVO { get; set; }
        public Nullable<int> C_TIPO { get; set; }
    
        public virtual ICollection<TBL_INGRESOS_X_USUARIO> TBL_INGRESOS_X_USUARIO { get; set; }
        public virtual TBL_TIPO_USUARIO TBL_TIPO_USUARIO { get; set; }
        public virtual ICollection<TBL_ENC_TORNEOS> TBL_ENC_TORNEOS { get; set; }
    }
}
