//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ENCUENTROS_X_TORNEO
    {
        public TBL_ENCUENTROS_X_TORNEO()
        {
            this.TBL_GOLEADORES = new HashSet<TBL_GOLEADORES>();
            this.TBL_POSICIONES = new HashSet<TBL_POSICIONES>();
        }
    
        public int C_CONSECUTIVO { get; set; }
        public Nullable<int> C_FK_ENC_TORNEO { get; set; }
        public Nullable<int> C_FK_LOCAL { get; set; }
        public Nullable<int> C_FK_VISITA { get; set; }
        public System.DateTime C_FECHA { get; set; }
        public short C_GOL_CASA { get; set; }
        public short C_GOL_VISITA { get; set; }
        public bool C_ESTADO { get; set; }
    
        public virtual TBL_ENC_TORNEOS TBL_ENC_TORNEOS { get; set; }
        public virtual TBL_EQUIPO TBL_EQUIPO { get; set; }
        public virtual TBL_EQUIPO TBL_EQUIPO1 { get; set; }
        public virtual ICollection<TBL_GOLEADORES> TBL_GOLEADORES { get; set; }
        public virtual ICollection<TBL_POSICIONES> TBL_POSICIONES { get; set; }
    }
}
