
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_V.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_INGRESOS_X_USUARIO
{

    public int C_CONSECUTIVO { get; set; }

    public int C_FK_USUARIO { get; set; }

    public System.DateTime C_INGRESO { get; set; }



    public virtual TBL_USUARIOS_LOG TBL_USUARIOS_LOG { get; set; }

}

}
