//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_V.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ENC_TORNEOS
    {
        public TBL_ENC_TORNEOS()
        {
            this.TBL_DETALLE_TORNEO = new HashSet<TBL_DETALLE_TORNEO>();
            this.TBL_ENCUENTROS_X_TORNEO = new HashSet<TBL_ENCUENTROS_X_TORNEO>();
            this.TBL_GOLEADORES = new HashSet<TBL_GOLEADORES>();
            this.TBL_TABLA_POSICIONES = new HashSet<TBL_TABLA_POSICIONES>();
        }
    
        public int C_CONSECUTIVO { get; set; }
        public int C_FK_USUARIO { get; set; }
        public System.DateTime C_FECHA_INICIAL { get; set; }
        public System.DateTime C_FECHA_FINAL { get; set; }
        public string C_NOMBRE_TORNEO { get; set; }
        public short C_CANT_EQUIPOS { get; set; }
        public bool C_ESTADO { get; set; }
    
        public virtual ICollection<TBL_DETALLE_TORNEO> TBL_DETALLE_TORNEO { get; set; }
        public virtual TBL_USUARIOS_LOG TBL_USUARIOS_LOG { get; set; }
        public virtual ICollection<TBL_ENCUENTROS_X_TORNEO> TBL_ENCUENTROS_X_TORNEO { get; set; }
        public virtual ICollection<TBL_GOLEADORES> TBL_GOLEADORES { get; set; }
        public virtual ICollection<TBL_TABLA_POSICIONES> TBL_TABLA_POSICIONES { get; set; }
    }
}
